use_frameworks!

platform :ios, '9.0'

target 'ZTThirdLibCategories_Example' do
  pod 'ZTThirdLibCategories', :path => '../'

  target 'ZTThirdLibCategories_Tests' do
    inherit! :search_paths

    
  end
end
